# Generated by Django 5.2.4 on 2025-07-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='conta',
            name='intervalo_meses',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='conta',
            name='recorrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conta',
            name='ultima_geracao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
